import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, test } from "vitest";
import { EVault } from "../src/entities/EVault.js";
import { VIRTUAL_DEPOSIT_AMOUNT } from "../src/entities/ERC4626Vault.js";

type OracleRow = [
	totalAssets: string,
	totalShares: string,
	amount: string,
	shares: string,
	assets: string,
	withdrawShares: string,
];

// These expected values are generated by the executable Lean definitions whose
// properties are proved in formal/lean/EulerArithmetic.lean. The full formal
// check verifies that this checked-in corpus is byte-identical to fresh output.
const rows: OracleRow[] = JSON.parse(
	readFileSync(new URL("../../../formal/lean/oracle.json", import.meta.url), "utf8"),
);

function snapshot(totalAssets: bigint, totalShares: bigint): EVault {
	// Use the real production methods against a fixed arithmetic snapshot. No RPC,
	// test-only reimplementation, unrelated vault metadata, or contract is involved.
	return Object.assign(Object.create(EVault.prototype) as EVault, {
		totalAssets,
		totalShares,
	});
}

test("the SDK virtual deposit and oracle corpus match the proved specification", () => {
	assert.equal(VIRTUAL_DEPOSIT_AMOUNT, 1_000_000n);
	assert.equal(rows.length, 497);
	assert(rows.some(([a]) => BigInt(a) === (1n << 256n) - 1n));
	assert(rows.some(([, , amount]) => BigInt(amount) === (1n << 53n) + 1n));
});

describe("EVault arithmetic agrees with the Lean evaluator", () => {
	for (const [index, row] of rows.entries()) {
		test(`oracle case ${index}: totals ${row[0]}/${row[1]}, amount ${row[2]}`, () => {
			const [totalAssets, totalShares, amount, shares, assets, withdrawShares] =
				row.map(BigInt);
			const vault = snapshot(totalAssets, totalShares);
			assert.equal(vault.convertToShares(amount), shares);
			assert.equal(vault.convertToAssets(amount), assets);
			assert.equal(vault.previewWithdraw(amount), withdrawShares);

			// Check theorem consequences against the actual TypeScript methods too.
			assert(vault.convertToAssets(withdrawShares) >= amount);
			if (withdrawShares > 0n) {
				assert(vault.convertToAssets(withdrawShares - 1n) < amount);
			}
			assert(vault.convertToAssets(shares) <= amount);
			assert(vault.convertToShares(assets) <= amount);
			assert(vault.convertToShares(amount + 1n) >= shares);
			assert(vault.convertToAssets(amount + 1n) >= assets);
			assert(vault.previewWithdraw(amount + 1n) >= withdrawShares);

			const adjustedAssets = totalAssets + VIRTUAL_DEPOSIT_AMOUNT;
			const adjustedShares = totalShares + VIRTUAL_DEPOSIT_AMOUNT;
			assert(shares * adjustedAssets <= amount * adjustedShares);
			assert(amount * adjustedShares < (shares + 1n) * adjustedAssets);
			assert(assets * adjustedShares <= amount * adjustedAssets);
			assert(amount * adjustedAssets < (assets + 1n) * adjustedShares);
			assert(amount * adjustedShares <= withdrawShares * adjustedAssets);
			assert(withdrawShares * adjustedAssets < amount * adjustedShares + adjustedAssets);
		});
	}
});
