export const swapVerifierAbi = [
	{
		type: "function",
		name: "transferFromSender",
		inputs: [
			{ name: "token", type: "address", internalType: "address" },
			{ name: "amount", type: "uint256", internalType: "uint256" },
			{ name: "to", type: "address", internalType: "address" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "transferBalanceFromSender",
		inputs: [
			{ name: "token", type: "address", internalType: "address" },
			{ name: "maxAmount", type: "uint256", internalType: "uint256" },
			{ name: "to", type: "address", internalType: "address" },
		],
		outputs: [{ name: "amount", type: "uint256", internalType: "uint256" }],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "aaveBorrowForSender",
		inputs: [
			{ name: "pool", type: "address", internalType: "address" },
			{ name: "asset", type: "address", internalType: "address" },
			{ name: "amount", type: "uint256", internalType: "uint256" },
			{ name: "to", type: "address", internalType: "address" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "morphoWithdrawCollateralForSender",
		inputs: [
			{ name: "morpho", type: "address", internalType: "address" },
			{
				name: "marketParams",
				type: "tuple",
				internalType: "struct IMorpho.MarketParams",
				components: [
					{ name: "loanToken", type: "address", internalType: "address" },
					{ name: "collateralToken", type: "address", internalType: "address" },
					{ name: "oracle", type: "address", internalType: "address" },
					{ name: "irm", type: "address", internalType: "address" },
					{ name: "lltv", type: "uint256", internalType: "uint256" },
				],
			},
			{ name: "amount", type: "uint256", internalType: "uint256" },
			{ name: "to", type: "address", internalType: "address" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "morphoBorrowForSender",
		inputs: [
			{ name: "morpho", type: "address", internalType: "address" },
			{
				name: "marketParams",
				type: "tuple",
				internalType: "struct IMorpho.MarketParams",
				components: [
					{ name: "loanToken", type: "address", internalType: "address" },
					{ name: "collateralToken", type: "address", internalType: "address" },
					{ name: "oracle", type: "address", internalType: "address" },
					{ name: "irm", type: "address", internalType: "address" },
					{ name: "lltv", type: "uint256", internalType: "uint256" },
				],
			},
			{ name: "amount", type: "uint256", internalType: "uint256" },
			{ name: "to", type: "address", internalType: "address" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "verifyAmountMinAndDeposit",
		inputs: [
			{ name: "vault", type: "address", internalType: "address" },
			{ name: "receiver", type: "address", internalType: "address" },
			{ name: "amountMin", type: "uint256", internalType: "uint256" },
			{ name: "deadline", type: "uint256", internalType: "uint256" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "verifyAmountMinAndSkim",
		inputs: [
			{ name: "vault", type: "address", internalType: "address" },
			{ name: "receiver", type: "address", internalType: "address" },
			{ name: "amountMin", type: "uint256", internalType: "uint256" },
			{ name: "deadline", type: "uint256", internalType: "uint256" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "verifyAmountMinAndTransfer",
		inputs: [
			{ name: "asset", type: "address", internalType: "address" },
			{ name: "receiver", type: "address", internalType: "address" },
			{ name: "amountMin", type: "uint256", internalType: "uint256" },
			{ name: "deadline", type: "uint256", internalType: "uint256" },
		],
		outputs: [],
		stateMutability: "nonpayable",
	},
	{
		type: "function",
		name: "verifyDebtMax",
		inputs: [
			{ name: "vault", type: "address", internalType: "address" },
			{ name: "account", type: "address", internalType: "address" },
			{ name: "amountMax", type: "uint256", internalType: "uint256" },
			{ name: "deadline", type: "uint256", internalType: "uint256" },
		],
		outputs: [],
		stateMutability: "view",
	},
	{ type: "error", name: "ControllerDisabled", inputs: [] },
	{ type: "error", name: "EVC_InvalidAddress", inputs: [] },
	{ type: "error", name: "NotAuthorized", inputs: [] },
	{ type: "error", name: "SwapVerifier_debtMax", inputs: [] },
	{ type: "error", name: "SwapVerifier_depositMin", inputs: [] },
	{ type: "error", name: "SwapVerifier_pastDeadline", inputs: [] },
	{ type: "error", name: "SwapVerifier_skimMin", inputs: [] },
	{ type: "error", name: "SwapVerifier_transferMin", inputs: [] },
] as const;
